standrewsdigital/digital-pattern-library

.core-stats.txt, src/_layouts/_base.hbs, src/examples/bootstrap.hbs, src/examples/bootstrap2.hbs, src/patterns/category-header/_category-header.scss, src/patterns/category-header/category-header.hbs, src/styles/doc.scss, src/styles/screen.scss
Updating the bootstrap and adv boostrap sections to use the University
header and menu.
=> MERGE (052 fixes)

package.json
=> MERGE (fixes) version numbers

SETUP.md
Update SETUP.md to follow style guide for Markdown files.
Update Git section to recommend Git command-line client, and recommended order of GUI clients.
Add information on how to easily locate your .gitconfig file (and how to exit the editor on Windows).
=> DOCS (SETUP.md) Improvements

CHANGELOG.md
Remove commit messages and convert to readable change log.
Update a few instances where house style for Markdown documents was not being followed.
=> MERGE (Change log) Remove commit messages

.core-stats.txt, src/docs/index.hbs
Sorry! Two broken links (about and development milestones) were broken.
=> MERGE (Fix links) Broken links on homepage

Gruntfile.js, README.md, package.json, src/_layouts/_base.hbs, src/_meta/dpl-nav.json, src/patterns/contact-card/contact-card.doc.hbs, src/patterns/info-bite-grid/info-bite-grid.doc.hbs, src/patterns/info-bite/info-bite.doc.hbs, src/patterns/masonry-grid/masonry-grid.doc.hbs, src/patterns/masonry/masonry.doc.hbs, src/patterns/text-banner/text-banner.doc.hbs
=> MERGE (Deprecation) Deprecate deploy components

package.json
Update version number to v0.7.0
=> MERGE (version number) bump to v0.7.0

SETUP.md
Correct repos to repositories.
Remove reference to ADD-PATTERN.md, which has now been merged in with CONTRIBUTING.md.
Bump version number.
=> MERGE (SETUP.md) Remove ADD-PATTERN.md reference

CHANGELOG.md, package.json, src/patterns/content-thirds/content-thirds.doc.hbs
Change fractions as 1/3 and 2/3 to &frac13; and &frac23; respectively.
Bump to v0.8.2
=> MERGE (Content thirds) Fix fractions

CONTRIBUTING.md, package.json
Modify section 4.9 to give instructions on adding new pattern to patterns page.
=> MERGE (CONTRIBUTING.md) Update how to add new pattern to pattern pages.

package.json, src/examples/bootstrap.hbs, src/examples/bootstrap2.hbs
Add navigation to Bootstrap components page.
Reorder (A-Z) and simplify navigation on Bootstrap components - advanced page.
=> MERGE (Bootstrap components) Tidy navigation

SETUP.md, package.json
Add section number for "Update an existing install" (now section 3).
Add section 4 for troubleshooting, and add steps to resolve "Error: handlebars does not support render".
Bump version number.
=> MERGE (Setup) Add troubleshooting section

package.json, src/patterns/featured-media/featured-media-options.json, src/patterns/featured-media/featured-media.doc.hbs
Fix missing images and remove redundant content from featured media.
Bump version to 0.9.0-rc2
=> MERGE (Featured media) Fix broken pattern

src/patterns/content-whole/content-whole.hbs
The wai aria role is not required for this pattern.
=> MERGE (Content whole) Remove wai aria role

CHANGELOG.md, package.json
=> MERGE (Content whole) Update CHANGELOG.md and package.json

CONTRIBUTING.md
Two sections 3.2 and 3.3. Renumber accordingly.
=> MERGE (Contributing Fix typo in section numbering for TOC

CHANGELOG.md, package.json, src/patterns/kis-widget/_kis-widget.scss, src/patterns/kis-widget/kis-widget.hbs
Add margin to the list item instead of the button.
=> MERGE (KIS widget) Modify css for kis button

CHANGELOG.md, package.json
=> MERGE (CHANGELOG) Update to v0.15.0

src/patterns/navigation-bar/_navigation-bar.scss, src/patterns/navigation-bar/navigation-bar.js
Change .JS code to use CSS classes instead of inline CSS.
=> MERGE (responsive-nav) Fix JS code

src/docs/index.hbs
This text has been signed off by Niall Scott, Director of Corporate Communications. I have changed one part, in the final paragraph, to aid clarity I have changed "Once explict, written sign-off" to "explicit and written".
=> MERGE (Homepage) Replace permissions text

src/patterns/kis-widget/_kis-widget.scss, src/patterns/sticky-nav/_sticky-nav.scss
Fix showing the widget on mobile
=> MERGE (KIS-widget) CSS adjustments

src/patterns/footer/footer.hbs
Moved code for affiliation logo above footer so it could be implemented in T4.
=> FIX (Footer) Affiliation logo

CHANGELOG.md, package.json
=> MERGE (CHANGELOG.md) Update changelog and version

CHANGELOG.md
=> MERGE (CHANGELOG.md) Correct changelog

CHANGELOG.md, package.json, src/scripts/datatables.js
There was a misplaced closing bracket that was showing as an error on the console.
=> MERGE (Datatables.js) Fix misplaced bracket

CHANGELOG.md, package.json, src/patterns/form-banner/_form-banner.scss, src/patterns/form-banner/form-banner-options.json, src/patterns/secondary-call/_secondary-call.scss, src/patterns/secondary-call/secondary-call-options.json, src/patterns/secondary-call/secondary-call.doc.hbs, src/patterns/secondary-call/secondary-call.hbs
Add documentation for third button, adjust styling to suit 3 buttons (or 2 or 1) and update the HBS file and options.json to better display multiple buttons.
=> FEAT (Secondary-call-to-action) Add third button option

src/patterns/kis-widget/_kis-widget.scss, src/patterns/kis-widget/kis-widget.hbs
KIS widget was dissapearing in tablet view
=> FIX (KIS widget) dissapearing in table

CHANGELOG.md, package.json, src/styles/screen.scss
New no-margin-bottom CSS rule created.
=> MERGE (dpl) New global CSS rule

CHANGELOG.md, package.json, src/patterns/staff-profile/staff-profile.doc.hbs
Change pattern rules to reflect new CSA team page.
=> DOCS (staff-profile) Update pattern rules

CHANGELOG.md, package.json, src/patterns/staff-profile/staff-profile.doc.hbs
Change rules to reflect new CSA team page.
=> DOCS (staff-profile) Update rules

src/patterns/content-thirds/_content-thirds.scss
No longer style text with grey background white.
=> Merge (content-thirds) Fix colour styling

CHANGELOG.md, package.json, src/styles/screen.scss
Remove min height CSS from col-xs-12 div.
=> MERGE (screen.scss) Fix min height

src/patterns/content-thirds/_content-thirds.scss
Text colour was black this has been changed to white when using a coloured background.
=> MERGE (Content-thirds) Fix text colour

CHANGELOG.md, package.json
=> MERGE (CHANGELOG.md) Update version

package.json
=> MERGE (package.json) Update version number

src/patterns/news-updates/news-updates-options.json, src/patterns/news-updates/news-updates.doc.hbs, src/patterns/news-updates/news-updates.hbs
New option in News updates pattern to be used in news site.
=> MERGE (news-updates) New option

src/patterns/buttons/_buttons.scss, src/patterns/buttons/buttons-options.json, src/patterns/buttons/buttons.hbs
Create new option under the Buttons pattern to illustrate buttons available on the news site.
=> MERGE (buttons) New options for news tags

src/patterns/featured-news/featured-news.js, src/patterns/more-news/_more-news.scss, src/patterns/more-news/more-news-options.json, src/patterns/more-news/more-news.doc.hbs, src/patterns/more-news/more-news.hbs, src/patterns/more-news/more-news.js, src/patterns/news-updates/news-updates.js
adjusted column widths and increased description length
=> MERGE (featured-news) column widths

CHANGELOG.md, src/patterns/featured-news/_featured-news.scss, src/patterns/featured-news/featured-news.hbs
=> MERGE (Featured news) Styling changes

src/patterns/contact-card/_contact-card.scss, src/patterns/panel/panel.scss, src/patterns/tile-grid/_tile-grid.scss
Box shadows on panels, tiles, and cards updated.
=> MERGE (drop-shadow) Shadows updated

src/patterns/featured-people/featured-people-options.json, src/patterns/featured-people/featured-people.doc.hbs
New max length of bio is now 200 chars
=> MERGE (featured-people) increased bio by 50 chars

src/patterns/featured-news/_featured-news.scss, src/patterns/featured-news/featured-news.hbs
Remove extra space under image when stacked and change to correct use of bootstrap nested columns
=> MERGE (featured-news) correct grid sizes and spacing

CHANGELOG.md, package.json, src/_layouts/_base.hbs, src/patterns/footer/footer.hbs
=> MERGE (FIX-footer) Correct the University title

src/_layouts/_base.hbs, src/_meta/patterns-page.json, src/patterns/navigation-bar/_navigation-bar.scss, src/patterns/navigation-bar/navigation-bar.hbs, src/patterns/navigation-bar/navigation-bar.js, src/patterns/search-bar/_search-bar.scss, src/patterns/search-bar/search-bar.hbs, src/styles/_icons.scss
Change chevron in main navigation bar
Change chevron in search bar dropdowns
Move navigation patterns higher up on all patterns page
Fix search bar dropdowns to open/close using keyboard
Fix deprecation issues with icons
=> FIX (chevron) replace png with fontawesome

CHANGELOG.md, package-lock.json, package.json, src/_layouts/_base.hbs, src/patterns/header/header.hbs
Update the search code to point to Funnelback instead of GSA
=> MERGE (FEAT-header) Update search code to point to Funnelback

src/patterns/featured-media/_featured-media.scss, src/patterns/featured-media/featured-media-options.json
Option for a caption below each image option and new colour options for featured media pattern.
=> FEAT (featured-media) Caption and new colour for featured media

CHANGELOG.md, package-lock.json, package.json, src/patterns/contact-card/_contact-card.scss
Card height increased at certain widths to cater for narrow and tall content.
=> FIX (contact) height issue

src/patterns/contact-card/_contact-card.scss, src/patterns/contact-card/contact-card-options.json
Cope with non-square images just incase
=> FEAT (contact card) image dimensions

src/styles/_bootstrap-theme.scss
=> FIX (misc) issues with floating hr

src/patterns/more-news/more-news.hbs, src/patterns/more-news/more-news.js
Allowance for publications to use this pattern for Schools Website
=> FIX (more news) greater flexibility of category link

src/patterns/kis-widget/_kis-widget.scss
To incorporate cookie notification alert
=> FIX (KIS widget) padding change

src/patterns/staff-profile/_staff-profile.scss
Fixed layout issue when no image present
=> FIX (staff profile) grid fix

src/patterns/contact-card/_contact-card.scss, src/patterns/contact-card/contact-card-options.json, src/patterns/contact-card/contact-card.hbs
Fix for non-square images
Summary intro text allowance
=> FEAT (contact card) school website amends

CHANGELOG.md, package-lock.json, package.json, src/docs/index.hbs, src/patterns/navigation-grid/_navigation-grid.scss, src/patterns/navigation-grid/navigation-grid-options.json, src/patterns/navigation-grid/navigation-grid.hbs, src/styles/vendor/bootstrap/_type.scss
Security patch
Minor updates to navigation grid pattern
=> FEAT (version update) v1.18.2

src/patterns/form-elements/_form-elements.scss, src/patterns/search-bar/search-bar.js, src/scripts/doc.js
updates to clear button to cope with typeahead form structure
=> FIX (search)

src/patterns/photosphere/photosphere.doc.hbs
Add disclaimer that pattern not supported by all browsers
=> FEAT (photosphere) disclaimer

package-lock.json, src/patterns/search-bar/search-bar.js
- dependencies
- remove console log
=> FIX (security)

CHANGELOG.md, package-lock.json, package.json, src/patterns/search-results/_search-results.scss, src/patterns/search-results/search-results.hbs
- version update docs
- style fix search results outline
=> DOCS (version update) v1.18.4

src/patterns/more-news/more-news-options.json, src/patterns/more-news/more-news.doc.hbs, src/patterns/navbox-grid/navbox-grid-options.json, src/patterns/navbox/navbox-options.json, src/patterns/navbox/navbox.doc.hbs, src/patterns/panel/panel-options.json, src/patterns/showcase-banner/showcase-banner-options.json, src/patterns/tile-grid/tile-grid.doc.hbs
Updated image sizes that were using old 360 x 240 standard size to 750 x 500.
=> FIX (image-sizes)

src/_partials/swatch.hbs, src/patterns/footer/_footer.scss, src/patterns/footer/footer-options.json, src/patterns/footer/footer.hbs, src/styles/_colors.scss, src/styles/_swatches.scss, src/styles/doc.scss, src/styles/screen.scss
Colour swatch removed transparent examples and fixed awards and affiliation logo banner sizing.
=> FEAT (colour swatch)

CHANGELOG.md, package.json
=> DOCS (CHANGELOG.md) Update version

src/patterns/accordion-deprecated/_accordion-deprecated.scss, src/patterns/accordion/accordion-options.json, src/patterns/accordion/accordion.hbs, src/patterns/accordion/accordion.js, src/patterns/facet-list/facet-list.hbs
- toggle button now optional
- fixes for aria roles automatically being applied
- deprecated accordion pattern colour change
=> FIX (accordion) toggle aria

package-lock.json, src/patterns/more-news/_more-news.scss, src/patterns/more-news/more-news-options.json, src/patterns/more-news/more-news.doc.hbs, src/patterns/more-news/more-news.hbs
Quick fixes to latest version v1.21.3
=> MERGE (more news)

package-lock.json, package.json, src/patterns/navbox/_navbox.scss, src/patterns/navbox/navbox.doc.hbs
=> MERGE (1.23.2)
